# webon
[build]
  # Comando que deseas usar
  command = "npm run build && npm run export"
  publish  = "out"

# Evita que se aplique el plugin Next.js
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
